# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2654b778e4013b73e72feb4b448059f3678817ee1208dfae2b6525197c33576934b61e5af3ca3385f7f21c3f91883951976e4651f22ce9c18e824749f51a087

test:
  secret_key_base: 73516d862f475f1628a21460971033d0d6443b808bee26efffbfd0f0214ed173e1e26dea7ce318c0c11ba5b296a76d6fc7828b1da5db3968d43c097835dfd63d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
